### ISSUE TITLE
Other vectorizations?

### ISSUE THREAD

**Issue by catanzaromj** [scikit-tda/pervect#2]
Thanks for the great package. I was wondering if there are plans to add support for additional vectorization schemes in persistent homology? In particular, I was wondering about persistence landscapes.

**Comment by ctralie** [comment]
This is definitely on our TODO list, but we are pretty swamped right now.
I also want to get in more efficient techniques for approximate bottleneck
and Wasserstein distance.  You are more than welcome to contribute pull
requests if you'd like!

**Comment by catanzaromj** [comment]
Sounds good and thanks for letting me know. I have some projects finishing up soon, so maybe I'll try implementing landscapes.

**Comment by ctralie** [comment]
That would be awesome!
